In [2]:
import pandas as pd
from selenium import webdriver
from pandas import DataFrame
from selenium.webdriver.common.keys import Keys
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

In [4]:
for i in range(10, 21):
    globals()['li{}'.format(i)] = pd.read_csv(f"trend_20{i}_2.csv", sep=",", index_col='Unnamed: 0', encoding='cp949')

In [5]:
listall = pd.concat([li20,li19,li18,li17,li16,li15,li14,li13,li12,li11,li10])

In [6]:
listall = listall.reset_index(drop=1)
listall = listall.set_index('제목', drop=True)

In [7]:
omg = pd.pivot_table(listall, index=['제목'], aggfunc = ['sum'])
omg

                         sum
                         관객수          매출액
제목
#살아있다                1900179  15947198820
0.0MHz                128147   1015400160
007 스카이폴             2355557  17337443500
007 스펙터              1795839  14104975630
100% 울프: 푸들이 될 순 없어    11958     95370220
...                      ...          ...
히트                    105344    741807000
히트맨                  2396652  20528241900
히트맨 NO.2 : 살인면허         1048      6906000
히트맨: 에이전트 47           60731    474744300
힘을 내요, 미스터 리         1142605   9645685276

[2646 rows x 2 columns]

In [25]:
listall.to_csv('trend_all.csv', encoding="cp949")

In [10]:
other = pd.read_csv("film_all3.csv", sep=",", encoding='cp949')
other.head()

,year,title,director_names,nations,genres,rate,영화제
0,2020,사탄은 없다,['모함마드 라술로프'],"[{'name': '독일'}, {'name': '이란'}, {'name': '체코'}]","['드라마', '액션']",평균 ★3.7 (28명),베를린
1,2020,노마드랜드,['클로이 자오'],"[{'name': '미국'}, {'name': '독일'}]",['드라마'],평균 ★3.8 (32명),베니스
2,2019,기생충,['봉준호'],[{'name': '한국'}],['드라마'],평균 ★4.3 (53만명),칸
3,2019,기생충,['봉준호'],[{'name': '한국'}],['드라마'],평균 ★4.3 (53만명),아카데미
4,2019,시너님스,['나다브 라피드'],"[{'name': '프랑스'}, {'name': '이스라엘'}, {'name': '...",['드라마'],평균 ★3.3 (261명),베를린

In [14]:
prize_audi = DataFrame()

In [11]:
list_tit = list(other['title'])
list_tit = set(list_tit)
list_tit = list(list_tit)
list_tit

['사랑의 유형',
 '더 그레이트 워',
 '카게무샤',
 '부시도',
 '날개',
 '메마른 여름',
 '그르바비차',
 '파우스트',
 '바운티호의 반란',
 '플래툰',
 '나라야마 부시코',
 '올 댓 재즈',
 '붉은 사막',
 '사랑의 메신저',
 '나막신 나무',
 '어센던시',
 '사물의 상태',
 '마테이 사건',
 '지상 최대의 쇼',
 '우리들의 낙원',
 '씨민과 나데르의 별거',
 '오데트',
 '뮤직 박스',
 '지난 해 마리앙바드에서',
 '신사협정',
 '천국으로 가는 노동계급',
 '더 스퀘어',
 '글래디에이터',
 '아마데우스',
 '비리디아나',
 '아메리칸 뷰티',
 '아무르',
 '위드아웃 리빙 언 어드레스 ',
 '핀치 콘티니의 정원',
 '알파빌',
 '이브의 모든 것',
 '더디 크레이비츠의 수습 기간',
 '대부',
 '조커',
 '섹스 거짓말 그리고 비디오테이프',
 '트라웃',
 '향혼녀',
 '녹색 광선',
 '아버지의 이름으로',
 'Palermo or Wolfsburg',
 '크래쉬',
 '흑인 오르페',
 '막달레나 시스터즈',
 '패왕별희',
 '책상 서랍 속의 동화',
 '언더그라운드',
 '더 차일드',
 '희미한 곰별자리',
 '누가 그의 죽음을 보았는가',
 '어둠 속의 댄서',
 '웨스트 사이드 스토리',
 '사계의 사나이',
 '애니 홀',
 '햄릿',
 '사랑의 행로',
 '붉은 수수밭',
 '라빠',
 '금지된 장난',
 '슬럼독 밀리어네어',
 '엘리트 스쿼드',
 '쉘부르의 우산',
 '컨버세이션',
 '보통 사람들',
 '카사블랑카',
 '이반의 어린 시절',
 '디어 헌터',
 '터치 미 낫',
 '셰익스피어 인 러브',
 '캔터베리 이야기',
 '테마',
 '스팅',
 '노인을 위한 나라는 없다',
 '뻐꾸기 둥지 위로 날아간 새',
 '시마론',
 '서부 전선 이상 없다',
 '피에타',
 '더 하우스 오브 스마일',
 '베라 드레이크',
 '래리 플린트',
 '용서받지 못한 자',
 '낵 앤 하우 투 겟 잇',
 '나, 다니엘 블레이크',
 '글로리아',
 '디아볼로',
 '썸웨어',
 '학이 난다',
 '데이비드',
 '로마',
 '밤',
 '왓 맥스 세드',
 '우리가 웃는 법',
 '패튼 대전차 군단',
 '레바논',
 '하나비',
 '빠드레 빠드로네',
 '아티스트',
 '우먼 앤드 더 스트레인저',
 '체리향기',
 '고양',
 '미니버 부인',
 '록키',
 '사탄의 태양 아래서',
 '제너럴 델라 로베레',
 '밤의 열기 속으로',
 '미드나잇 카우보이',
 '아들의 방',
 '얼리 웍스',
 '파리 텍사스',
 '산타 바바라의 맹세',
 '엉클 분미',
 '대부 2',
 '양들의 침묵',
 '영험한 애주가의 전설',
 '피아노',
 '파리의 아메리카인',
 '하트랜드',
 '더 랫츠',
 '포 인 어 지프',
 '셰이프 오브 워터: 사랑의 모양',
 '남과 여',
 '양철북',
 '아들의 자리',
 '두 여인',
 '애정의 조건',
 '방랑자',
 '아쎈소르',
 '투야의 결혼',
 '비밀과 거짓말',
 '지상에서 영원으로',
 '캐벌케이드',
 '센스 앤 센서빌리티',
 '무호마츠의 일생',
 '성스러운 도로',
 '웨더비',
 '밀크 오브 소로우 - 슬픈 모유',
 '화씨 9/11',
 '그랜드 캐년',
 '버드맨',
 '트리 오브 라이프',
 '아파트 열쇠를 빌려드립니다',
 '숏컷',
 '에밀 졸라의 생애',
 '써클',
 '도시 위에 군림하는 손',
 '늑대와 춤을',
 '로젠크란츠와 길덴스턴은 죽었다',
 '지지',
 '막다른 골목',
 '잃어버린 주말',
 '크로나카 파밀리아레',
 '노마드랜드',
 '벤허',
 '씬 레드 라인',
 '택시',
 '모두가 왕의 부하들',
 '마티',
 '피아니스트',
 '침묵의 세계',
 '드라이빙 미스 데이지',
 '엘리펀트',
 '4개월, 3주... 그리고 2일',
 '만약',
 '불의 전차',
 '광란의 사랑',
 '어느날 밤에 생긴 일',
 '브레이브하트',
 '그린 북',
 '질주',
 '기생충',
 '최선의 의도',
 '바톤 핑크',
 '윈터 슬립',
 '백일염화',
 '공포의 보수',
 '디파티드',
 '허니',
 '애정만세',
 '이토록 긴 부재',
 '잉글리쉬 페이션트',
 '시카고',
 '남쪽 사람',
 '우리 생애 최고의 해',
 '줄 위의 종달새',
 '로미오와 줄리엣',
 '브로크백 마운틴',
 '중앙역',
 '씨클로',
 '베로니카 포스의 갈망',
 '아라비아의 로렌스',
 '더 스트라이크',
 '인 디스 월드',
 '카르멘',
 '결혼 피로연',
 '가장 따뜻한 색, 블루',
 '보리밭을 흔드는 바람',
 '80일간의 세계일주',
 '킹스 스피치',
 '욕망',
 '시너님스',
 '블러디 선데이',
 '홉슨의 사위 고르기',
 '우정어린 설득',
 '미녀 갱 카르멘',
 '달콤한 인생',
 '세 가지 색 : 블루',
 '간디',
 '크레이머 대 크레이머',
 '시그노르 & 시그노리',
 '사촌들',
 '레인 맨',
 '정복자 펠레',
 '욜',
 '하얀 리본',
 '아르고',
 '마농',
 '올리버',
 '비둘기, 가지에 앉아 존재를 성찰하다',
 '라인강을 넘어',
 '아푸 제2부 - 아파라지토',
 '스포트라이트',
 '매쉬',
 '조용한 태양의 해',
 '산딸기',
 '비정성시',
 '프렌치 커넥션',
 '나의 계곡은 푸르렀다',
 '출발',
 '어느 가족',
 '로제타',
 '반지의 제왕 : 왕의 귀환',
 '독일 자매',
 '비포 더 레인',
 '센과 치히로의 행방불명',
 '세브린느',
 '화염의 바다',
 '하수인',
 '굿바이 칠드런',
 '스틸 라이프',
 '마지막 황제',
 '허수아비',
 '아웃 오브 아프리카',
 '알제리 전투',
 '철의 사나이',
 '지옥의 묵시록',
 '우리는 같은 꿈을 꾼다',
 '레오파드',
 '신데렐라',
 '사운드 오브 뮤직',
 '불타는 해의 연대기',
 '레베카',
 '쉬탐하임',
 '문라이트',
 '아틀란틱 시티',
 '쉰들러 리스트',
 '톰 존스의 화려한 모험',
 '택시 드라이버',
 '더 레슬러',
 '떠나간 여인',
 '우르가',
 '리턴',
 '대지의 눈물',
 '의문의 실종',
 '위대한 지그펠드',
 '먼 곳으로부터',
 '원 섬머 오브 해피니스',
 '미치고 싶을 때',
 '재판은 끝났다',
 '라쇼몽',
 '12명의 성난 사람들',
 '인버테이션 투 더 댄스',
 '클래스',
 '마이클 콜린스',
 '인 비버 밸리',
 '사탄은 없다',
 '영원과 하루',
 '콰이강의 다리',
 '노예 12년',
 '매그놀리아',
 '나의 길을 가련다',
 '바람과 함께 사라지다',
 '뷰티풀 마인드',
 '시저는 죽어야 한다',
 '디판',
 '마이 페어 레이디',
 '펄프 픽션',
 '밀리언 달러 베이비',
 '워터프론트',
 '몬순 웨딩',
 '그랜드 호텔',
 '포레스트 검프',
 '타이타닉',
 '귀주 이야기',
 '미션',
 '서커스 돔 위의 예술가',
 '벌집',
 '허트 로커',
 '아빠는 출장 중',
 '색, 계',
 '엘 라사리요 데 토르메스',
 '우나기',
 '정사',
 '브로드웨이 멜로디']

In [15]:
for i in list_tit:
    try:
        aa = DataFrame(omg.loc[f'{i}'])
        aa = aa.transpose()
        prize_audi = prize_audi.append(aa)
    except:
        pass

In [16]:
prize_audi = prize_audi.reset_index()
prize_audi.columns = ['제목', '관객수', '매출액']
prize_audi

                   제목       관객수          매출액
0               더 스퀘어      4141     35134300
1                  조커   5229027  45215057210
2           슬럼독 밀리어네어      4360     26112000
3       노인을 위한 나라는 없다      3147     29245000
4                 피에타    592343   4274347500
5         나, 다니엘 블레이크     25500    201753200
6                아티스트     10884     78824000
7   셰이프 오브 워터: 사랑의 모양    477941   3969822300
8                남과 여    155727   1274742733
9                 버드맨    167989   1357898100
10          트리 오브 라이프     28120    194886500
11                 벤허   1383215  11274091695
12              불의 전차      1951     12462000
13               그린 북    319767   2693498708
14                기생충  10252659  86963603405
15          잉글리쉬 페이션트     13167    107821000
16           로미오와 줄리엣      1627     12857000
17       가장 따뜻한 색, 블루      3394     18428000
18             킹스 스피치    797156   5897269000
19                아르고    136102    969566000
20             스포트라이트    251662   2021684087
21              어느 가족    123614   1037979700
22       센과 치히로의 행방불명    110813    871002700
23               신데렐라    708631   5441839200
24               문라이트    117809    949053295
25            쉰들러 리스트      1239      6207500
26             노예 12년    484493   3542270100
27        바람과 함께 사라지다   4859883  34276270161
28               타이타닉    356297   4307363000
29              허트 로커    164633   1230909500
30               색, 계      1735     12848500

In [18]:
prize_audi.to_csv('prize_audi.csv', encoding="cp949")