In [1]:
import pandas as pd

In [2]:
flim_all = pd.read_csv("flim_all.csv", encoding='cp949')
flim_all

,year,title,director_names,nations,genres,rate,영화제
0,2020,사탄은 없다,['모함마드 라술로프'],"[{'name': '독일'}, {'name': '이란'}, {'name': '체코'}]","['드라마', '액션']",평균 ★3.7 (28명),베를린
1,2020,노마드랜드,['클로이 자오'],"[{'name': '미국'}, {'name': '독일'}]",['드라마'],평균 ★3.8 (32명),베니스
2,2019,기생충,['봉준호'],[{'name': '한국'}],['드라마'],평균 ★4.3 (53만명),칸
3,2019,기생충,['봉준호'],[{'name': '한국'}],['드라마'],평균 ★4.3 (53만명),아카데미
4,2019,시너님스,['나다브 라피드'],"[{'name': '프랑스'}, {'name': '이스라엘'}, {'name': '...",['드라마'],평균 ★3.3 (261명),베를린
...,...,...,...,...,...,...,...
308,1932,그랜드 호텔,['에드먼드 굴딩'],[{'name': '미국'}],"['로맨스', '드라마']",평균 ★3.5 (508명),아카데미
309,1931,시마론,['웨슬리 러글스'],[{'name': '미국'}],['드라마'],평균 ★2.9 (202명),아카데미
310,1930,서부 전선 이상 없다,['루이스 마일스톤'],[{'name': '미국'}],"['전쟁', '드라마']","평균 ★3.7 (2,910명)",아카데미
311,1929,브로드웨이 멜로디,['해리 부몽'],[{'name': '미국'}],[],평균 ★3.0 (200명),아카데미
312,1927,날개,['윌리엄 A. 웰먼'],[{'name': '미국'}],['전쟁'],평균 ★3.2 (277명),아카데미

In [3]:
for i in range(len(flim_all["director_names"])):
    flim_all["director_names"][i] = flim_all["director_names"][i][1:-1]
    flim_all["director_names"][i] = flim_all["director_names"][i].replace("'","")

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [4]:
for i in range(len(flim_all["genres"])):
    flim_all["genres"][i] = flim_all["genres"][i][1:-1]
    flim_all["genres"][i] = flim_all["genres"][i].replace("'","")

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [5]:
for i in range(len(flim_all["nations"])):
    flim_all["nations"][i] = flim_all["nations"][i][1:-1]
    flim_all["nations"][i] = flim_all["nations"][i].replace("{","")
    flim_all["nations"][i] = flim_all["nations"][i].replace("}","")
    flim_all["nations"][i] = flim_all["nations"][i].replace("'name': ","")
    flim_all["nations"][i] = flim_all["nations"][i].replace("'","")

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
for i in range(len(flim_all["rate"])):
    flim_all["rate"][i] = flim_all["rate"][i].replace("평균 ★","")

In [8]:
flim_all

,year,title,director_names,nations,genres,rate,영화제
0,2020,사탄은 없다,모함마드 라술로프,"독일, 이란, 체코","드라마, 액션",3.7 (28명),베를린
1,2020,노마드랜드,클로이 자오,"미국, 독일",드라마,3.8 (32명),베니스
2,2019,기생충,봉준호,한국,드라마,4.3 (53만명),칸
3,2019,기생충,봉준호,한국,드라마,4.3 (53만명),아카데미
4,2019,시너님스,나다브 라피드,"프랑스, 이스라엘, 독일",드라마,3.3 (261명),베를린
...,...,...,...,...,...,...,...
308,1932,그랜드 호텔,에드먼드 굴딩,미국,"로맨스, 드라마",3.5 (508명),아카데미
309,1931,시마론,웨슬리 러글스,미국,드라마,2.9 (202명),아카데미
310,1930,서부 전선 이상 없다,루이스 마일스톤,미국,"전쟁, 드라마","3.7 (2,910명)",아카데미
311,1929,브로드웨이 멜로디,해리 부몽,미국,,3.0 (200명),아카데미
312,1927,날개,윌리엄 A. 웰먼,미국,전쟁,3.2 (277명),아카데미

In [9]:
flim_all.to_csv("flim_all2.csv", encoding='cp949')